language: node_js
node_js:
  - 8

branches:
  only:
    - master

script:
  - "npm run lint"
  - "npm run build"

cache:
  directories:
    - node_modules

dist: trusty

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist/
  on:
    branch: master